# Generated by Django 5.0.1 on 2025-03-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_education_profile_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
